#!/bin/bash
# Main entry point for jit

ROOT=$(dirname "$0")
CMD=$1
ARGS=( "${@:2}" )

# Attempt to call command file
FILE="$ROOT/cmd/$CMD.sh"

if [[ -f $FILE ]]
then
  $FILE "${ARGS[@]}"
else
  git "$CMD" "${ARGS[@]}"
fi
