#!/bin/bash
# Makes a GitHub fork of the given repo & clones locally
# usage: git-clone <username> <reponame>

echo 'Command not implemented'
exit 1

# fork the repo on GitHub
gh repo fork --clone=false $1/$2
# possible to automatically say no to cloning?
# `echo 'n' | gh repo fork $1/$2` doesn't seem to work

# make a clone

# working dir should be named by the main branch
# i.e. if default branch is '2.9', then clone to
#   ~/git/juju/juju/2.9


