#!/bin/bash
# usage: git-where push <branch>
#    or  git where pull <branch>


# https://stackoverflow.com/a/9753364

if [ $# -ge 2 ]
then
  BRANCH=$2
else
  BRANCH=HEAD
fi


if [ $1 = push ]
then
  git for-each-ref --format='%(push:short)' $(git rev-parse --symbolic-full-name $BRANCH)
elif [ $1 = pull ]
then
  git for-each-ref --format='%(upstream:short)' $(git rev-parse --symbolic-full-name $BRANCH)
fi
