name: "Test"
on: [push, pull_request, workflow_dispatch]

jobs:
  go-test:
    name: "Run Go tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v5

      - name: Set up Git config
        run: |
          # This needs to be done for the gitserver test
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: "Run Go tests"
        run: go test ./...
